### ISSUE TITLE
Regarding OHLCV program

### ISSUE THREAD

**Issue by raviyellani** [upendrasingh12/Algorithmic-trading#1]
Does OHLCV program is working, can we test it or its in under development

**Comment by s13rw81** [comment]
```python
data1 = fyers.get_historical_OHLCV(
AttributeError: 'FyersModel' object has no attribute 'get_historical_OHLCV'```

I dont think this endpoint is working. Will wait for @upendrasingh12 to confirm.

**Comment by upendrasingh12** [comment]
Fyers no longer provides data on its own. We can either use third party service provided by fyers to fetch the data or we can use another data vendor's service for the same.
